---
new_page_extension: md
auto_deploy: false
admin_path: admin
webhook_url: 
sections:
- type: heading
  label: Content
- type: directory
  path: content/articles
  label: Articles
  create: all
  match: "**/*"
  templates:
  - article
- type: directory
  path: content/authors
  label: Authors
  create: all
  match: "**/*"
  templates:
  - author
- type: directory
  path: contet/categories
  label: Categories
  create: all
  match: "**/*"
  templates:
  - category
- type: directory
  path: content/issues
  label: Issues
  create: all
  match: "**/*"
  templates:
  - issue
- type: heading
  label: Website
- type: document
  path: content/pages/about.md
  label: About Us
- type: document
  path: content/pages/pressroom.md
  label: Press Room
- type: document
  path: content/pages/privacy.md
  label: Privacy Policy
- type: document
  path: content/pages/support.md
  label: Support Us
- type: document
  path: content/pages/tos.md
  label: Terms of use
upload_dir: static
public_path: ''
front_matter_path: ''
use_front_matter_path: 
file_template: ":filename:"
build:
  install_dependencies_command: npm install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run develop
